# Generated by Django 3.1.2 on 2021-11-15 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado Activo'),
        ),
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
