# Generated by Django 3.1.2 on 2021-11-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211114_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_usuario',
            name='cargo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
