# Generated by Django 3.1.2 on 2021-11-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211115_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuarios',
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_quiz',
            field=models.CharField(choices=[('1', 'Preguntas'), ('2', 'VOZ'), ('3', 'Cartas'), ('4', 'VIDEOS')], default='3', max_length=2),
        ),
    ]
